[package]
name = "pyrustmpi"
version = "0.1.0"
edition = "2018"

[lib]
name = "pyrustmpi"
crate-type = ["lib", "cdylib"]

[dependencies]
pyo3 = { version = "0.16", features = ["auto-initialize"] }
mpi = { git = "https://github.com/rsmpi/rsmpi", branch = "main"}