{% set data = load_setup_py_data(setup_file='setup.py') %}

package:
  name: pyrustmpi
  version: {{data.version}}

source:
  path: ..

build:
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python