package:
  name: pyrustmpi
  version: 1.0.0

source:
  path: ../

requirements:
  build:
    - gcc
    - clang

  host:
    - {{ mpi }}
    - rust
    - python {{ python }}
    - pip
    - maturin
    - cffi >=1.15

  run:
    - {{ mpi }}
    - python {{ python }}
    - mpi4py
    - numpy 1.22.2
    - cffi >=1.15

build:
  name: pyrustmpi-{{ mpi }}-py{{ python }}
  noarch: generic
  script: maturin build && python -m pip install .
