name: Publish To Anaconda

on: [push]

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.8"]

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3

      # - name: Install GCC (MacOS)
      #   if: runner.os == 'macOS'
      #   run: |
      #     bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      #     brew install gcc

      - name: Install Conda Build
        shell: bash -l {0}
        run: conda install conda-build

      - name: Build
        shell: bash -l {0}
        run: conda build -c conda-forge -c anaconda conda.recipe --py ${{ matrix.python-version }}

      - name: Install Anaconda Client
        shell: bash -l {0}
        run: conda install anaconda-client

      - name: Upload (${{ matrix.python-version }}, ${{ matrix.os }})
        if: runner.os == 'Linux'
        run: anaconda -t ${{ secrets.ANACONDA }} upload --force --user skailasa  /usr/share/miniconda/envs/test/conda-bld/linux-64/pyrustmpi-*.tar.bz2
        if: runner.os == 'macOS'
        run: anaconda -t ${{ secrets.ANACONDA }} upload --force --user skailasa  /usr/share/miniconda/envs/test/conda-bld/osx-64/pyrustmpi-*.tar.bz2
